name: three_seven
description: 3-7 card game built with Flutter
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  uuid: ^4.4.2
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/cards/backs/
    - assets/cards/faces/
    - assets/cards/faces/hearts/
    - assets/cards/faces/spades/
    - assets/cards/faces/diamonds/
    - assets/cards/faces/clubs/

